import json
import hashlib
from pathlib import Path
from PySide6.QtCore import QObject, Property, Signal, Slot, QUrl

import ui_messages
from epub_reader import (acquire_cache_lease, discard_cache_root, open_epub,
                         release_cache_root, retain_cache_root,
                         schedule_discard_cache_root, web_page)
from storage_context import StorageContext


def epub_signature(path, stat=None):
    path = Path(path).resolve()
    stat = stat or path.stat()
    return (str(path), stat.st_dev, stat.st_ino, stat.st_size,
            stat.st_mtime_ns, stat.st_ctime_ns)


def prepare_epub(path, *, cache_identity=None, edition_identity=None,
                 storage_context=None):
    """Prepare an EPUB entirely outside the QML/Qt object graph."""
    storage = storage_context or StorageContext.production()
    storage.assert_test_safe()
    path = Path(path).resolve()
    for _ in range(2):
        before = path.stat()
        opened = open_epub(
            path, storage.cache_root, cache_identity=cache_identity,
            edition_identity=edition_identity, acquire_lease=True,
            producer_scope=storage.purpose, cache_budget=storage.cache_budget)
        if isinstance(opened, tuple):
            book, lease = opened
        else:  # Test doubles written for the pre-lease API remain valid.
            book = opened
            lease = acquire_cache_lease(book.get('root'))
        try:
            metadata = path.parent.parent / '.epub-source.json'
            translation_source_hash = ''
            if metadata.is_file():
                translation_source_hash = json.loads(metadata.read_text()).get('sha256', '')
            after = path.stat()
            before_key = epub_signature(path, before)
            after_key = epub_signature(path, after)
            if before_key == after_key:
                return dict(path=str(path), signature=after_key, book=book,
                            source_hash=book['source_hash'],
                            translation_source_hash=translation_source_hash,
                            logical_identity=str(cache_identity or path),
                            edition_identity=str(edition_identity or path),
                            _lease=lease)
        except Exception:
            if lease:
                lease.release()
            raise
        if lease:
            lease.release()
    raise OSError('EPUB 正在替换，请稍后重试')


def release_prepared(prepared, *, discard=False):
    """Release a worker payload that the GUI did not adopt."""
    if not isinstance(prepared, dict):
        return
    lease = prepared.pop('_lease', None)
    root = str((prepared.get('book') or {}).get('root') or '')
    if lease:
        lease.release()
    if discard and root:
        schedule_discard_cache_root(root)


def prepared_page(book, chapter):
    root = Path(book['root']).resolve()
    relative = (book.get('portals') or {}).get(chapter)
    if relative:
        path = (root / relative).resolve()
        if path.is_relative_to(root) and path.is_file():
            return path
    # Compatibility for old caches and focused unit-test doubles. Production
    # v6 generations have every local HTML portal prepared by the worker.
    return web_page(book, chapter)


def _project_chapter(chapter: dict) -> dict:
    """Display projection of one chapter: localized state and fallback label.

    ``generatedTitle`` marks a label this application invented.  Only those are
    re-rendered in the interface locale; a publisher title that happens to read
    like a default label stays exactly as published.
    """
    generated = bool(chapter.get('generatedTitle'))
    title = str(chapter.get('title') or '')
    if generated:
        index = chapter.get('generatedIndex')
        if index:
            title = ui_messages.render(
                ui_messages.Message(ui_messages.MessageCode.EPUB_DEFAULT_SECTION, (index,)))
    state = ui_messages.epub_state_code(chapter.get('translationState'))
    return {**chapter, 'title': title,
            'translationState': ui_messages.render(ui_messages.Message(state)) if state else '',
            'translationStateCode': state}


def _project_bookmark(mark: dict, chapters: list[dict]) -> dict:
    """Localize only titles explicitly marked as generated by WhaleRead."""
    row = dict(mark)
    if mark.get('generated_title') is not True:
        return row
    try:
        chapter_index = int(mark.get('chapter', -1))
        chapter = chapters[chapter_index]
        percent = int(mark.get('percent', round(float(mark.get('fraction', 0)) * 100)))
    except (TypeError, ValueError, IndexError):
        return row
    row['title'] = ui_messages.render(ui_messages.Message(
        ui_messages.MessageCode.EPUB_BOOKMARK, (chapter.get('title', ''), percent)))
    return row


class EpubSession(QObject):
    changed = Signal()
    scrollRequested = Signal(float)
    wheelRequested = Signal(float)

    def __init__(self, owner):
        super().__init__(owner)
        self.settings = owner.owner.settings
        self.storage_context = owner.owner.storage_context
        self.book = {}
        self.path = ''
        self.chapter = 0
        self.fraction = 0.
        self.error = ''
        self.current_url = ''
        self.source_hash = ''
        self.translation_source_hash = ''
        self.logical_identity = ''
        self.edition_identity = ''
        self._pending_prepared = None
        self._current_cache_root = ''
        self._pending_cache_root = ''
        self._retired_cache_roots = {}
        self._current_lease = None
        self._pending_lease = None
        self._retired_leases = {}

    def key(self, suffix):
        if self.logical_identity:
            identity = hashlib.sha256(
                (self.logical_identity + '\0' + self.edition_identity).encode()).hexdigest()
            return 'epub/v2/' + identity + '/' + suffix
        return self.legacy_key(suffix)

    def legacy_key(self, suffix):
        identity = (hashlib.sha256(self.path.encode()).hexdigest()
                    if self.path and (Path(self.path).parent.parent / '.epub-source.json').is_file()
                    else self.book.get('digest', ''))
        return 'epub/' + identity + '/' + suffix

    def setting_value(self, suffix, default, value_type):
        key = self.key(suffix)
        if self.settings.contains(key):
            return self.settings.value(key, default, type=value_type)
        legacy = self.legacy_key(suffix)
        if legacy != key and self.settings.contains(legacy):
            value = self.settings.value(legacy, default, type=value_type)
            self.settings.setValue(key, value)
            return value
        return default

    def _marks(self):
        try:
            value = json.loads(self.setting_value('marks', '[]', str))
            return [dict(row) for row in value if isinstance(row, dict)] if isinstance(value, list) else []
        except (TypeError, ValueError):
            return []

    def _set_cache_root(self, attribute, root):
        root = str(root or '')
        previous = getattr(self, attribute, '')
        if previous == root:
            return
        if root:
            retain_cache_root(root)
        setattr(self, attribute, root)
        if previous:
            release_cache_root(previous)

    def _discard_cache(self, root):
        # Deterministic isolated QA can assert reclamation immediately. The
        # installed application moves filesystem deletion off the GUI thread.
        if self.storage_context.purpose == 'production':
            schedule_discard_cache_root(root)
        else:
            discard_cache_root(root)

    @staticmethod
    def _same_cache_edition(left, right):
        return bool(left and right and Path(left).parent == Path(right).parent)

    def _retire_cache_root(self, root, replacement):
        """Hold an old page until WebKit confirms that its replacement loaded."""
        root = str(root or '')
        if not root or root == str(replacement or ''):
            return
        disposable = self._same_cache_edition(root, replacement)
        if root not in self._retired_cache_roots:
            retain_cache_root(root)
            self._retired_cache_roots[root] = disposable
        elif disposable:
            self._retired_cache_roots[root] = True

    @staticmethod
    def _lease_for_prepared(prepared):
        lease = prepared.pop('_lease', None)
        if lease is not None:
            return lease
        return acquire_cache_lease((prepared.get('book') or {}).get('root'))

    def _retire_current_lease(self, root):
        lease, self._current_lease = self._current_lease, None
        if lease is None:
            return
        previous = self._retired_leases.get(root)
        if previous is not None:
            lease.release()
        else:
            self._retired_leases[root] = lease

    def _adopt(self, prepared):
        old_root = self._current_cache_root
        new_root = str(prepared['book'].get('root') or '')
        new_lease = self._lease_for_prepared(prepared)
        if old_root and old_root != new_root:
            # If an unseen checkpoint is already prepared, it is the newest
            # on-disk generation for the old edition. Keep that generation and
            # retire the visible older one as disposable.
            replacement = (self._pending_cache_root
                           if self._same_cache_edition(old_root, self._pending_cache_root)
                           else new_root)
            self._retire_cache_root(old_root, replacement)
            self._retire_current_lease(old_root)
        elif old_root == new_root and self._current_lease is not None:
            if new_lease:
                new_lease.release()
            new_lease = self._current_lease
        elif self._current_lease is not None:
            self._current_lease.release()
        self._set_cache_root('_current_cache_root', new_root)
        self._current_lease = new_lease
        self._set_cache_root('_pending_cache_root', '')
        if self._pending_lease is not None:
            self._pending_lease.release()
            self._pending_lease = None
        self._pending_prepared = None
        self._signature = tuple(prepared['signature'])
        self.path = str(prepared['path'])
        self.book = dict(prepared['book'])
        self.error = ''
        self.current_url = ''
        self.source_hash = str(prepared.get('source_hash') or '')
        self.translation_source_hash = str(prepared.get('translation_source_hash') or '')
        self.logical_identity = str(prepared.get('logical_identity') or '')
        self.edition_identity = str(prepared.get('edition_identity') or '')
        chapters = self.book.get('chapters', [])
        self.chapter = min(max(0, self.setting_value('chapter', 0, int)),
                           max(0, len(chapters) - 1))
        self.fraction = min(1., max(0., self.setting_value('fraction', 0., float)))

    def accept_prepared(self, prepared, *, defer_same_path=True):
        signature = tuple(prepared['signature'])
        if signature == getattr(self, '_signature', None):
            release_prepared(prepared)
            return False
        if defer_same_path and self.path == str(prepared['path']) and self.book:
            self._signature = signature
            old_prepared = self._pending_prepared
            self._pending_prepared = prepared
            new_lease = self._lease_for_prepared(prepared)
            old_pending = self._pending_cache_root
            self._set_cache_root('_pending_cache_root', prepared['book'].get('root', ''))
            if self._pending_lease is not None:
                self._pending_lease.release()
            self._pending_lease = new_lease
            if old_pending and old_pending != self._pending_cache_root:
                self._discard_cache(old_pending)
            if old_prepared is not None:
                release_prepared(old_prepared)
            self.changed.emit()
            return True
        self._adopt(prepared)
        self.changed.emit()
        return True

    def open(self, path, *, cache_identity=None, edition_identity=None):
        path = Path(path).resolve()
        try:
            signature = epub_signature(path)
        except OSError:
            signature = (str(path), None, None)
        if signature == getattr(self, '_signature', None):
            return False
        # A checkpoint rewrites the archive, hence its cache URL. Never swap the
        # document underneath a reader: percentage restoration is not a text
        # anchor, and even an unchanged chapter would visibly reload.
        if self.path == str(path) and self.book:
            try:
                prepared = prepare_epub(
                    path, cache_identity=cache_identity,
                    edition_identity=edition_identity,
                    storage_context=self.storage_context)
            except Exception:
                return False  # Keep the last verified page; retry on the next poll.
            return self.accept_prepared(prepared)
        try:
            prepared = prepare_epub(
                path, cache_identity=cache_identity,
                edition_identity=edition_identity,
                storage_context=self.storage_context)
        except Exception as exc:
            self.error = str(exc)
            self.changed.emit()
            return False
        return self.accept_prepared(prepared)

    @Property('QVariantMap', notify=changed)
    def state(self):
        # Chapters are projected for display only: an app-generated default
        # label is localized, a publisher title is passed through untouched.
        chapters = [_project_chapter(chapter) for chapter in self.book.get('chapters', [])]
        marks = [_project_bookmark(mark, chapters) for mark in self._marks()]
        return dict(active=bool(self.path), title=self.book.get('title', Path(self.path).stem), error=self.error,
                    chapters=chapters, chapter=self.chapter, fraction=self.fraction,
                    root=QUrl.fromLocalFile(self.book['root'] + '/').toString() if self.book else '',
                    url=self.current_url or (QUrl.fromLocalFile(str(prepared_page(self.book, chapters[self.chapter]['path']))).toString() if chapters else ''),
                    marks=marks, fixed=self.book.get('fixed', False), updateAvailable=self._pending_prepared is not None)

    def _apply_pending(self):
        if self._pending_prepared is not None:
            prepared = self._pending_prepared
            old_root = self._current_cache_root
            if old_root and old_root != self._pending_cache_root:
                self._retire_cache_root(old_root, self._pending_cache_root)
                self._retire_current_lease(old_root)
            elif old_root == self._pending_cache_root:
                if self._pending_lease is not None:
                    self._pending_lease.release()
                self._pending_lease = self._current_lease
            self._set_cache_root('_current_cache_root', self._pending_cache_root)
            self._current_lease = self._pending_lease
            self._pending_lease = None
            self._set_cache_root('_pending_cache_root', '')
            self.book = dict(prepared['book'])
            self.source_hash = str(prepared.get('source_hash') or '')
            self.translation_source_hash = str(prepared.get('translation_source_hash') or '')
            self.logical_identity = str(prepared.get('logical_identity') or self.logical_identity)
            self.edition_identity = str(prepared.get('edition_identity') or self.edition_identity)
            self._pending_prepared = None

    def close(self):
        current, pending = self._current_cache_root, self._pending_cache_root
        retired = dict(self._retired_cache_roots)
        self._set_cache_root('_current_cache_root', '')
        self._set_cache_root('_pending_cache_root', '')
        self._retired_cache_roots = {}
        for lease in (self._current_lease, self._pending_lease):
            if lease is not None:
                lease.release()
        self._current_lease = self._pending_lease = None
        for lease in self._retired_leases.values():
            lease.release()
        self._retired_leases = {}
        for root in retired:
            release_cache_root(root)
        # A prepared checkpoint is newer than the still-visible generation.
        # Preserve the new cache for the next open and retire only the old one.
        if self._same_cache_edition(current, pending):
            self._discard_cache(current)
        for root, disposable in retired.items():
            if disposable:
                self._discard_cache(root)
        self._pending_prepared = None
        self._signature = None
        self.path = ''
        self.book = {}
        self.error = ''
        self.current_url = ''
        self.source_hash = ''
        self.translation_source_hash = ''
        self.logical_identity = ''
        self.edition_identity = ''

    @Slot()
    def releasePreviousCache(self):  # noqa: N802
        retired = dict(self._retired_cache_roots)
        self._retired_cache_roots = {}
        for root, disposable in retired.items():
            lease = self._retired_leases.pop(root, None)
            if lease is not None:
                lease.release()
            release_cache_root(root)
            # A cache from another book/edition remains its latest warm copy.
            # Only an older generation of the same edition is superseded.
            if disposable and root not in {self._current_cache_root,
                                           self._pending_cache_root}:
                self._discard_cache(root)

    @Slot()
    def updateChapter(self):
        # Explicit refresh may reflow the page. Automatic progress never does.
        self.navigate(self.chapter, self.fraction)

    @Slot(int, float)
    def navigate(self, chapter, fraction):
        if not self.book:
            return
        self._apply_pending()
        self.chapter = max(0, min(chapter, len(self.book['chapters'])-1))
        self.current_url = ''
        self.savePosition(fraction)
        self.settings.setValue(self.key('chapter'), self.chapter)
        self.changed.emit()

    @Slot(str)
    def openLink(self, raw):
        url = QUrl(raw)
        if not self.book or not url.isLocalFile():
            return
        path = Path(url.toLocalFile()).resolve()
        root = Path(self.book['root']).resolve()
        if not path.is_relative_to(root) or path.suffix.lower() not in {'.html', '.xhtml', '.htm'}:
            return
        relative = path.relative_to(root).as_posix()
        self._apply_pending()
        if self.book['root'] != str(root):
            url = QUrl.fromLocalFile(str(Path(self.book['root']) / relative))
            url.setFragment(QUrl(raw).fragment())
            raw = url.toString()
        for i, chapter in enumerate(self.book['chapters']):
            if chapter['path'] == relative:
                self.chapter = i
        portal = QUrl.fromLocalFile(str(prepared_page(self.book, relative)))
        portal.setFragment(QUrl(raw).fragment())
        self.current_url = portal.toString()
        self.fraction = 0.
        self.settings.setValue(self.key('chapter'), self.chapter)
        self.savePosition(0.)
        self.changed.emit()

    @Slot(float)
    def savePosition(self, fraction):
        if self.book:
            self.fraction = min(1., max(0., fraction))
            self.settings.setValue(self.key('fraction'), self.fraction)

    @Slot(float)
    def bookmark(self, fraction):
        if not self.book:
            return
        marks = self._marks()
        if not any(m['chapter'] == self.chapter and abs(m['fraction'] - fraction) < .01 for m in marks):
            chapter = self.book['chapters'][self.chapter]
            percent = round(fraction * 100)
            marks.append(dict(
                chapter=self.chapter, fraction=fraction,
                title=str(chapter.get('title') or '') + f' · {percent}%',
                generated_title=True,
                chapter_generated_title=bool(chapter.get('generatedTitle')),
                chapter_generated_index=int(chapter.get('generatedIndex') or 0),
                percent=percent,
            ))
            self.settings.setValue(self.key('marks'), json.dumps(marks, ensure_ascii=False))
            self.changed.emit()

    @Slot(int)
    def removeBookmark(self, index):
        marks = self._marks()
        if 0 <= index < len(marks):
            marks.pop(index)
            self.settings.setValue(self.key('marks'), json.dumps(marks, ensure_ascii=False))
            self.changed.emit()
